apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-resources 
  namespace: pod-resources 
spec: 
  containers: 
  - image: nginx:1.16 
    name: nginx-resources 
  resources: 
    requests:  #Minimium 
      cpu: "20m" 
      memory: "15Mi"
    limits:    #Maximum
      memory: "20Mi"
      cpu: "40m"
