apiVersion: v1 
kind: Pod 
metadata: 
name: nginx-secret 
spec: 
  containers: 
  - image: nginx:1.16 
    name: nginx-secret 
    env: 
    - name: COOL_VARIABLE 
      valueFrom: 
        secretKeyRef: 
          name: another-secret 
          key: key1 
          
# kubectl apply -f nginx-secret.yaml
